// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvWOMyaH1BuetGHzWSD_9vHZ7ZWhObmIg',
    appId: '1:98529474187:web:ddbc034ad59932a068868e',
    messagingSenderId: '98529474187',
    projectId: 'commutenepal-d601d',
    authDomain: 'commutenepal-d601d.firebaseapp.com',
    databaseURL: 'https://commutenepal-d601d-default-rtdb.firebaseio.com',
    storageBucket: 'commutenepal-d601d.appspot.com',
    measurementId: 'G-ZX50R138VM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLqjokL7wM3eTiDQ6u1Q-dvSxaWYZ-zSo',
    appId: '1:98529474187:android:d4815a231bc76c5968868e',
    messagingSenderId: '98529474187',
    projectId: 'commutenepal-d601d',
    databaseURL: 'https://commutenepal-d601d-default-rtdb.firebaseio.com',
    storageBucket: 'commutenepal-d601d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6u8VZovykRj1UfS111Nyi-OvA5tX34hw',
    appId: '1:98529474187:ios:c672ff3168782f1c68868e',
    messagingSenderId: '98529474187',
    projectId: 'commutenepal-d601d',
    databaseURL: 'https://commutenepal-d601d-default-rtdb.firebaseio.com',
    storageBucket: 'commutenepal-d601d.appspot.com',
    androidClientId: '98529474187-837420s3ejhjmelj815sf1hsnaqe6mth.apps.googleusercontent.com',
    iosClientId: '98529474187-tdj5bktfsg4e98pk80uh5quksh7pcno9.apps.googleusercontent.com',
    iosBundleId: 'com.example.commuteNepal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6u8VZovykRj1UfS111Nyi-OvA5tX34hw',
    appId: '1:98529474187:ios:c672ff3168782f1c68868e',
    messagingSenderId: '98529474187',
    projectId: 'commutenepal-d601d',
    databaseURL: 'https://commutenepal-d601d-default-rtdb.firebaseio.com',
    storageBucket: 'commutenepal-d601d.appspot.com',
    androidClientId: '98529474187-837420s3ejhjmelj815sf1hsnaqe6mth.apps.googleusercontent.com',
    iosClientId: '98529474187-tdj5bktfsg4e98pk80uh5quksh7pcno9.apps.googleusercontent.com',
    iosBundleId: 'com.example.commuteNepal',
  );
}
